import { Open_Sans } from 'next/font/google';
import '../styles/globals.css';
import { Auth } from '../contexts/auth';

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  display: 'swap',
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={openSans.className}>
      <body>
        <Auth>{children}</Auth>
      </body>
    </html>
  );
}