import '../styles/globals.css';
import {Auth} from '../contexts/auth'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Auth>
          {children}
        </Auth>
      </body>
    </html>
  )
}
